Webpa replace
Comcast/parodus2ccsp pull request #231
Opened 2022-06-13 11:20 UTC by vasuki01

2022-06-13 17:31 UTC, shilpa24balaji commented on source/broadband/webpa_replace.c
> +        WalInfo("paramName after mapping : %s\n",paramName);
Revert the info log changes

2022-06-14 06:32 UTC, sadhyama requested changes

2022-06-14 06:32 UTC, sadhyama commented on source/broadband/webpa_replace.c
> +#define RBUS_ENABLE  "Device.DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.RBUS.Enable"
Add this TR181 in a common .h file - webpa_internal.h

2022-06-14 06:32 UTC, sadhyama commented on source/broadband/webpa_replace.c
> +                if(((strncmp(isRbus, "true", strlen("true")) == 0) && parameterInfo[cnt]->writable == 2) ||
Add null check for isRbus . 
Can we avoid doing multiple string operations for each parameter in for loop, by adding null check and defining a flag variable at the beginning and use that flag to to decide if it is rbus/dbus mode .

2022-06-14 06:32 UTC, sadhyama commented on source/broadband/webpa_replace.c
> +                   ((strncmp(isRbus, "false", strlen("false")) == 0) && parameterInfo[cnt]->writable == 1))
add a comment line also on this change as return value of writable info is different for dbus/rbus modes

2022-06-15 07:45 UTC, sadhyama requested changes

2022-06-15 07:45 UTC, sadhyama commented on source/broadband/webpa_replace.c
> +	    rbusMode = (strncmp(isRbus, "true", strlen("true")) == 0) ? 1 : 0;
Can you move this check to line 502 just after GET and log an error when isRbus is NULL

2022-06-15 07:45 UTC, sadhyama commented on source/broadband/webpa_replace.c
> +    WalInfo("Rbus =%s\n", isRbus);
log it when isRbus is not null

2022-06-16 05:51 UTC, sadhyama requested changes

2022-06-16 05:51 UTC, sadhyama commented on source/broadband/webpa_replace.c
> +	if(isRbus != NULL)
Move this to line 502 just after GET

2022-06-16 05:51 UTC, sadhyama commented on source/broadband/webpa_replace.c
> +		WalInfo("isRbus is NULL\n");
Add it as WalError

2022-06-16 06:27 UTC, sadhyama approved these changes

2022-06-21 12:11 UTC, merged